using System;
using System.Collections.Generic;
using System.Globalization;

namespace ShotV.Core;

public static class GameText
{
    public const string ChineseLocale = "zh-CN";
    public const string EnglishLocale = "en-US";

    private static readonly IReadOnlyDictionary<string, string> EmptyTable = new Dictionary<string, string>();

    private static readonly Dictionary<string, IReadOnlyDictionary<string, string>> Tables = new()
    {
        [ChineseLocale] = new Dictionary<string, string>
        {
            ["item.salvage-scrap.label"] = "废料块",
            ["item.salvage-scrap.short"] = "废料",
            ["item.salvage-scrap.description"] = "基础回收件，占位小但容易塞满背包。",
            ["item.telemetry-cache.label"] = "遥测数据",
            ["item.telemetry-cache.short"] = "遥测",
            ["item.telemetry-cache.description"] = "可转换为研究进度的数据缓存。",
            ["item.alloy-plate.label"] = "合金板",
            ["item.alloy-plate.short"] = "合金",
            ["item.alloy-plate.description"] = "中型结构材料，回收后补充合金库存。",
            ["item.aegis-core.label"] = "主核残片",
            ["item.aegis-core.short"] = "主核",
            ["item.aegis-core.description"] = "高价值主核残片，体积大但回收价值极高。",
            ["item.ammo-mg-ball.label"] = "机枪标准弹",
            ["item.ammo-mg-ball.short"] = "标准",
            ["item.ammo-mg-ball.description"] = "机枪标准备用弹药。60 发封顶一格。",
            ["item.ammo-mg-ap.label"] = "机枪穿甲弹",
            ["item.ammo-mg-ap.short"] = "穿甲",
            ["item.ammo-mg-ap.description"] = "机枪穿甲备用弹药。60 发封顶一格。",
            ["item.ammo-mg-hp.label"] = "机枪高损弹",
            ["item.ammo-mg-hp.short"] = "高损",
            ["item.ammo-mg-hp.description"] = "机枪高损备用弹药。60 发封顶一格。",
            ["item.ammo-mg-tracer.label"] = "机枪曳光弹",
            ["item.ammo-mg-tracer.short"] = "曳光",
            ["item.ammo-mg-tracer.description"] = "机枪曳光备用弹药。60 发封顶一格。",
            ["item.ammo-mg-bonded.label"] = "机枪粘结弹",
            ["item.ammo-mg-bonded.short"] = "粘结",
            ["item.ammo-mg-bonded.description"] = "机枪粘结备用弹药。60 发封顶一格。",
            ["item.ammo-gl-frag.label"] = "破片榴弹",
            ["item.ammo-gl-frag.short"] = "破片",
            ["item.ammo-gl-frag.description"] = "破片榴弹备用弹药。60 发封顶一格。",
            ["item.ammo-gl-breach.label"] = "破甲榴弹",
            ["item.ammo-gl-breach.short"] = "破甲",
            ["item.ammo-gl-breach.description"] = "破甲榴弹备用弹药。60 发封顶一格。",
            ["item.ammo-gl-arc.label"] = "电弧榴弹",
            ["item.ammo-gl-arc.short"] = "电弧",
            ["item.ammo-gl-arc.description"] = "电弧榴弹备用弹药。60 发封顶一格。",
            ["item.ammo-gl-blast.label"] = "重爆榴弹",
            ["item.ammo-gl-blast.short"] = "重爆",
            ["item.ammo-gl-blast.description"] = "重爆榴弹备用弹药。60 发封顶一格。",
            ["item.ammo-gl-flechette.label"] = "箭簇榴弹",
            ["item.ammo-gl-flechette.short"] = "箭簇",
            ["item.ammo-gl-flechette.description"] = "箭簇榴弹备用弹药。60 发封顶一格。",
            ["item.ammo-sn-match.label"] = "精确狙击弹",
            ["item.ammo-sn-match.short"] = "精确",
            ["item.ammo-sn-match.description"] = "精确狙击备用弹药。60 发封顶一格。",
            ["item.ammo-sn-sabot.label"] = "脱壳狙击弹",
            ["item.ammo-sn-sabot.short"] = "脱壳",
            ["item.ammo-sn-sabot.description"] = "脱壳狙击备用弹药。60 发封顶一格。",
            ["item.ammo-sn-exp.label"] = "高爆狙击弹",
            ["item.ammo-sn-exp.short"] = "高爆",
            ["item.ammo-sn-exp.description"] = "高爆狙击备用弹药。60 发封顶一格。",
            ["item.ammo-sn-overmatch.label"] = "超配狙击弹",
            ["item.ammo-sn-overmatch.short"] = "超配",
            ["item.ammo-sn-overmatch.description"] = "超配狙击备用弹药。60 发封顶一格。",
            ["item.ammo-sn-rupture.label"] = "裂伤狙击弹",
            ["item.ammo-sn-rupture.short"] = "裂伤",
            ["item.ammo-sn-rupture.description"] = "裂伤狙击备用弹药。60 发封顶一格。",
            ["item.med-injector.label"] = "治疗针",
            ["item.med-injector.short"] = "治疗针",
            ["item.med-injector.description"] = "战区常见的单次应急治疗剂，可快速恢复生命。",
            ["item.field-kit.label"] = "战地急救包",
            ["item.field-kit.short"] = "急救包",
            ["item.field-kit.description"] = "占位更大，但能一次性恢复更多生命。",
            ["item.shock-charge.label"] = "震爆罐",
            ["item.shock-charge.short"] = "震爆",
            ["item.shock-charge.description"] = "以自身为中心释放高压震爆，适合清开近身敌人。",
            ["item.dash-cell.label"] = "机动电池",
            ["item.dash-cell.short"] = "机动",
            ["item.dash-cell.description"] = "重置冲刺冷却并立刻补上一段机动脉冲。",

            ["weapon.MachineGun.label"] = "机枪",
            ["weapon.MachineGun.hint"] = "30 发弹匣，中距离压制主武器。",
            ["weapon.Grenade.label"] = "榴弹",
            ["weapon.Grenade.hint"] = "6 发弹匣的榴弹发射器，适合轰散密集敌群。",
            ["weapon.Sniper.label"] = "狙击",
            ["weapon.Sniper.hint"] = "5 发弹匣，远距离点杀与穿透主武器。",

            ["ammo.ammo-mg-ball.label"] = "标准",
            ["ammo.ammo-mg-ball.hint"] = "标准弹，稳定压制。",
            ["ammo.ammo-mg-ap.label"] = "穿甲",
            ["ammo.ammo-mg-ap.hint"] = "穿甲弹，对中甲更稳。",
            ["ammo.ammo-mg-hp.label"] = "高损",
            ["ammo.ammo-mg-hp.hint"] = "高损弹，对轻甲更凶。",
            ["ammo.ammo-mg-tracer.label"] = "曳光",
            ["ammo.ammo-mg-tracer.hint"] = "曳光弹链，护甲表现略弱，但贯穿更稳定。",
            ["ammo.ammo-mg-bonded.label"] = "粘结",
            ["ammo.ammo-mg-bonded.hint"] = "粘结弹芯，兼顾混合装甲与软目标。",
            ["ammo.ammo-gl-frag.label"] = "破片",
            ["ammo.ammo-gl-frag.hint"] = "标准破片榴弹。",
            ["ammo.ammo-gl-breach.label"] = "破甲",
            ["ammo.ammo-gl-breach.hint"] = "破甲榴弹，对重型目标更强。",
            ["ammo.ammo-gl-arc.label"] = "电弧",
            ["ammo.ammo-gl-arc.hint"] = "电弧榴弹，覆盖更广。",
            ["ammo.ammo-gl-blast.label"] = "重爆",
            ["ammo.ammo-gl-blast.hint"] = "高装药榴弹，终端伤害更高，但破片扩散更短。",
            ["ammo.ammo-gl-flechette.label"] = "箭簇",
            ["ammo.ammo-gl-flechette.hint"] = "反人员箭簇载荷，适合扫过密集目标。",
            ["ammo.ammo-sn-match.label"] = "精确",
            ["ammo.ammo-sn-match.hint"] = "标准精确弹。",
            ["ammo.ammo-sn-sabot.label"] = "脱壳",
            ["ammo.ammo-sn-sabot.hint"] = "脱壳穿甲弹，贯穿更强。",
            ["ammo.ammo-sn-exp.label"] = "高爆",
            ["ammo.ammo-sn-exp.hint"] = "高爆狙击弹，终端伤害更高。",
            ["ammo.ammo-sn-overmatch.label"] = "超配",
            ["ammo.ammo-sn-overmatch.hint"] = "重型狙击弹，兼顾破甲与多目标延续。",
            ["ammo.ammo-sn-rupture.label"] = "裂伤",
            ["ammo.ammo-sn-rupture.hint"] = "针对软目标的杀伤弹，终端伤害极高但贯穿有限。",

            ["hostile.Melee.label"] = "追猎体",
            ["hostile.Ranged.label"] = "射击体",
            ["hostile.Charger.label"] = "冲锋体",
            ["hostile.Boss.label"] = "神盾主核",

            ["route.combat-sandbox-route.label"] = "前线穿廊",
            ["route.combat-sandbox-route.summary"] = "由外环码头切入，穿过中继巢区，最后从货运升降机撤离。",
            ["route.foundry-loop-route.label"] = "熔炉环线",
            ["route.foundry-loop-route.summary"] = "线路更短、节奏更快，适合高频刷取基础资源。",
            ["route.frost-wharf-route.label"] = "霜港折返",
            ["route.frost-wharf-route.summary"] = "寒区港口副本，占位内容为主，后续会接入低能见度和环境危害。",
            ["route.archive-drop-route.label"] = "资料库坠层",
            ["route.archive-drop-route.summary"] = "档案设施副本，目前是结构空壳，后续用于高价值情报线。",
            ["route.blackwell-route.label"] = "黑井穿梭",
            ["route.blackwell-route.summary"] = "竖井运输副本，现阶段提供路线选择壳子，后续接入垂直区域和平台交互。",

            ["zone.perimeter-dock.label"] = "外围码头",
            ["zone.perimeter-dock.description"] = "入口压力较低，适合确认手感和路线。",
            ["zone.relay-nest.label"] = "中继巢区",
            ["zone.relay-nest.description"] = "敌群密度明显抬升，但回收效率也更高。",
            ["zone.vault-approach.label"] = "金库前厅",
            ["zone.vault-approach.description"] = "高价值区入口，敌人更耐打，掉落更偏向合金与研究样本。",
            ["zone.freight-lift.label"] = "货运升降机",
            ["zone.freight-lift.description"] = "终端撤离出口，完成压制后即可带走整局战利品。",
            ["zone.slag-yard.label"] = "废渣场",
            ["zone.slag-yard.description"] = "短线入口区，适合试火后快速撤离。",
            ["zone.smelter-core.label"] = "熔炉核心",
            ["zone.smelter-core.description"] = "高压中段区域，合金产出更稳定。",
            ["zone.rail-elevator.label"] = "轨道电梯",
            ["zone.rail-elevator.description"] = "路线终点，清空后可直接结束本轮行动。",
            ["zone.ice-dock.label"] = "冰封泊位",
            ["zone.ice-dock.description"] = "风压低、敌情轻，适合作为副本壳子占位。",
            ["zone.cold-storage.label"] = "冷库连廊",
            ["zone.cold-storage.description"] = "占位区域，预留给环境交互和冻结机制。",
            ["zone.breaker-gate.label"] = "破冰闸门",
            ["zone.breaker-gate.description"] = "临时出口，后续会替换为完整副本终点事件。",
            ["zone.surface-stack.label"] = "表层书库",
            ["zone.surface-stack.description"] = "安静但视野复杂，适合作为探索模板。",
            ["zone.index-shaft.label"] = "索引井道",
            ["zone.index-shaft.description"] = "占位区，后续会塞入密码门和资料采集交互。",
            ["zone.sealed-vault.label"] = "封存库厅",
            ["zone.sealed-vault.description"] = "终点出口，占位版本仅保留基础推进流程。",
            ["zone.shaft-mouth.label"] = "井口平台",
            ["zone.shaft-mouth.description"] = "进场平台，保留快速撤离口。",
            ["zone.maintenance-ring.label"] = "维护环廊",
            ["zone.maintenance-ring.description"] = "占位中段，用于后续平台切换和环形战区。",
            ["zone.deep-anchor.label"] = "深层锚点",
            ["zone.deep-anchor.description"] = "深层出口，当前只保留地图与结算骨架。",

            ["marker.entry.label"] = "投送点",
            ["marker.extraction.label"] = "撤离出口",
            ["marker.command.label"] = "指挥台",
            ["marker.locker.label"] = "储物柜",
            ["marker.workshop.label"] = "工坊台",
            ["marker.launch.label"] = "出击闸门",

            ["common.empty"] = "空",
            ["common.close"] = "关闭",
            ["common.selected"] = "已选定",
            ["common.unavailable"] = "不可用",
            ["common.no_focus"] = "无焦点",
            ["common.no_cost"] = "无消耗",
            ["common.no_base_stock"] = "无基地库存",
            ["common.no_weapons"] = "未装备武器",
            ["common.no_carried_resources"] = "无携行资源",

            ["overlay.dock.kicker.tactical"] = "战术链路",
            ["overlay.dock.kicker.deploy"] = "部署链路",
            ["overlay.settlement.kicker"] = "结算链路",
            ["overlay.button.deploy"] = "部署行动",
            ["overlay.button.extract_now"] = "立即撤离",
            ["overlay.card.result"] = "行动结果",
            ["overlay.card.battle"] = "战斗数据",
            ["overlay.card.resources"] = "资源回收",
            ["overlay.card.loot"] = "物资结算",
            ["overlay.footnote.settlement"] = "确认后返回基地，仓储无法容纳的携行物资会计入遗失。",
            ["overlay.button.confirm_settlement"] = "确认结算并返回基地",
            ["overlay.headline.base"] = "基地待命",
            ["overlay.headline.combat_default"] = "战区行动",
            ["overlay.subline.connecting"] = "正在接入行动数据",
            ["overlay.subline.result"] = "结果：{0}",
            ["overlay.subline.current_zone"] = "{0} / 威胁 {1} / {2}",
            ["overlay.subline.open_area"] = "开放区域行动",
            ["overlay.hint.base"] = "前往出击闸门后再部署。",
            ["overlay.hint.combat"] = "前往撤离点结束行动，或继续在区域内探索。",
            ["overlay.primary.deploy"] = "部署行动",
            ["overlay.primary.not_ready"] = "部署未就绪",
            ["overlay.primary.confirm_return"] = "确认结算并返回基地",
            ["overlay.primary.extract"] = "执行撤离",
            ["overlay.outcome.boss_clear"] = "区域压制",
            ["overlay.outcome.down"] = "行动失败",
            ["overlay.outcome.extracted"] = "成功撤离",
            ["overlay.duration.seconds"] = "{0} 秒",
            ["overlay.duration.minutes"] = "{0} 分 {1:00} 秒",
            ["overlay.resource_bundle"] = "废料 {0} / 合金 {1} / 研究 {2}",
            ["overlay.loot_more"] = "{0} 等 {1} 项",
            ["overlay.settlement.title.down"] = "行动中止 / 结算确认",
            ["overlay.settlement.title.return"] = "行动结算 / 返回确认",
            ["overlay.settlement.time"] = "用时 {0}",
            ["overlay.settlement.kills"] = "击杀 {0}",
            ["overlay.settlement.wave"] = "最高波次 {0}",
            ["overlay.settlement.loss"] = "损失：{0}",
            ["overlay.settlement.lost"] = "遗失：{0}",
            ["overlay.extraction.boss_clear_with_zone"] = "{0}压制完成",
            ["overlay.extraction.boss_clear"] = "地图压制完成",
            ["overlay.extraction.down"] = "行动失败",
            ["overlay.extraction.extracted_with_zone"] = "已从{0}撤离",
            ["overlay.extraction.extracted"] = "成功撤离",

            ["fullscreen.panel.kicker"] = "行动面板",
            ["fullscreen.panel.footer"] = "按 Tab 关闭面板，按 M 打开全图。",
            ["fullscreen.base_banner.title"] = "基地营区 / {0}",
            ["fullscreen.overview.base_title"] = "基地总览 / {0}",
            ["fullscreen.overview.base_meta"] = "焦点：{0}\n图例：玩家 / 视角 / 标记",
            ["fullscreen.overview.base_hint"] = "查看基地设施、地图情报和出击闸门。按 M 关闭。",
            ["fullscreen.overview.current_region"] = "当前区域",
            ["fullscreen.overview.meta"] = "焦点：{0}\n敌人：{1} / 附近掉落：{2}",
            ["fullscreen.panel.title.locker"] = "储物柜 / 仓储",
            ["fullscreen.panel.title.workshop"] = "工坊 / 配装",
            ["fullscreen.panel.title.command"] = "指挥 / 情报",
            ["fullscreen.panel.title.launch"] = "出击 / 部署",
            ["fullscreen.panel.title.combat_inventory"] = "战斗背包 / 掉落",
            ["fullscreen.panel.title.base_overview"] = "基地总览",
            ["fullscreen.panel.title.mission_overview"] = "任务总览",
            ["fullscreen.panel.meta.selected_map"] = "当前地图：{0}",
            ["fullscreen.panel.meta.workshop"] = "配装顺序会同步到武器槽 1 / 2 / 3。制作出的消耗品会进入仓储。",
            ["fullscreen.panel.meta.stored_items"] = "仓储物品：{0}",
            ["fullscreen.panel.meta.deployment_target"] = "部署目标：{0} / 已装入物品：{1}",
            ["fullscreen.card.resources"] = "资源",
            ["fullscreen.card.map"] = "地图",
            ["fullscreen.card.stash"] = "仓储",
            ["fullscreen.card.selected_map"] = "当前地图",
            ["fullscreen.card.current_stash"] = "当前仓储",
            ["fullscreen.card.current_stash_meta"] = "打开储物柜查看物品详情并自动整理。",
            ["fullscreen.card.workshop"] = "工坊",
            ["fullscreen.card.workshop_meta"] = "打开工坊调整武器槽使用的配装顺序。",
            ["fullscreen.card.last_extraction"] = "上次撤离",
            ["fullscreen.card.region"] = "区域",
            ["fullscreen.card.loadout"] = "配装",
            ["fullscreen.card.runtime"] = "运行数据",
            ["fullscreen.card.runtime_value"] = "击杀：{0}\n附近掉落：{1}",
            ["fullscreen.card.ao"] = "行动区域",
            ["fullscreen.card.ao_meta"] = "开放区域战斗进行中。",
            ["fullscreen.card.pack"] = "背包",
            ["fullscreen.card.pack_value"] = "携带物品：{0}",
            ["fullscreen.card.pack_meta"] = "快捷栏：{0}",
            ["fullscreen.card.loot"] = "掉落",
            ["fullscreen.card.loot_value"] = "地面掉落：{0}",
            ["fullscreen.card.loot_meta"] = "附近可拾取：{0}",
            ["fullscreen.locker.info_title"] = "仓储信息",
            ["fullscreen.locker.info_value"] = "仓储物品：{0}",
            ["fullscreen.locker.info_meta"] = "基地储物柜用于存放组件、回收件和制作材料。",
            ["fullscreen.workshop.header"] = "配装配置",
            ["fullscreen.workshop.weapon_slot"] = "武器槽",
            ["fullscreen.workshop.move_up"] = "上移",
            ["fullscreen.workshop.move_down"] = "下移",
            ["fullscreen.workshop.fabrication"] = "制作",
            ["fullscreen.workshop.blueprint"] = "蓝图",
            ["fullscreen.workshop.cost"] = "消耗：{0}",
            ["fullscreen.workshop.in_stash"] = "仓储存量：{0}",
            ["fullscreen.workshop.ready"] = "可制作并存入基地仓储。",
            ["fullscreen.workshop.fabricate"] = "制作",
            ["fullscreen.command.pressure"] = "区域 {0} / 最高威胁 {1} / 撤离点 {2}",
            ["fullscreen.command.select_map"] = "选择地图",
            ["fullscreen.launch.regional_pressure"] = "区域压力",
            ["fullscreen.launch.pressure_value"] = "最高威胁 {0} / 区域 {1}",
            ["fullscreen.launch.high_risk_hint"] = "高风险地图：建议部署前至少携带一件治疗消耗品。",
            ["fullscreen.launch.low_risk_hint"] = "低风险地图允许空部署包，但不建议这样做。",
            ["fullscreen.launch.deployment_status"] = "部署状态",
            ["fullscreen.launch.pack_summary"] = "背包概要",
            ["fullscreen.launch.pack_summary_value"] = "物品 {0} / 格位 {1}/{2}",
            ["fullscreen.launch.pack_summary_meta"] = "治疗 {0} / 机动 {1} / 工具 {2}",
            ["fullscreen.launch.pack_label"] = "部署包",
            ["fullscreen.action.auto_arrange"] = "自动整理",
            ["fullscreen.action.rotate_loadout"] = "轮换配装",
            ["fullscreen.action.cycle_map"] = "切换地图",
            ["fullscreen.action.deploy"] = "部署",
            ["fullscreen.action.sort_pack"] = "整理背包",
            ["fullscreen.tab.overview"] = "总览",
            ["fullscreen.tab.locker"] = "仓储",
            ["fullscreen.tab.workshop"] = "工坊",
            ["fullscreen.tab.command"] = "情报",
            ["fullscreen.tab.launch"] = "出击",
            ["fullscreen.tab.inventory"] = "背包",
            ["fullscreen.quick_slot.empty"] = "{0}：空",
            ["fullscreen.quick_slot.item"] = "{0}：{1}",
            ["fullscreen.base_resources"] = "废料 {0} / 合金 {1} / 研究 {2}",
            ["fullscreen.resource.scrap"] = "废料 {0}",
            ["fullscreen.resource.alloy"] = "合金 {0}",
            ["fullscreen.resource.research"] = "研究 {0}",
            ["fullscreen.region_intel"] = "{0}级 / {1} / {2} / {3} / {4} / {5}",
            ["fullscreen.extraction.allowed"] = "可撤离",
            ["fullscreen.extraction.blocked"] = "不可撤离",
            ["fullscreen.supply.high"] = "建议部署包至少带一件治疗品、一件机动工具和一件范围控场消耗品。",
            ["fullscreen.supply.mid"] = "建议至少带一件治疗品和一件泛用工具后再进入更深区域。",
            ["fullscreen.supply.low"] = "轻装也能进入，但最好仍预留一份保底治疗。",
            ["fullscreen.map_summary"] = "开放地图 / 区域 {0} / 最高威胁 {1} / 撤离点 {2}",
            ["fullscreen.zone_kind.Perimeter"] = "外围区",
            ["fullscreen.zone_kind.HighRisk"] = "高风险",
            ["fullscreen.zone_kind.HighValue"] = "高价值",
            ["fullscreen.zone_kind.Extraction"] = "撤离区",
            ["fullscreen.zone_kind.Open"] = "开放区域",
            ["fullscreen.region_pressure.highrisk_high"] = "密集冲锋体",
            ["fullscreen.region_pressure.highrisk"] = "混合敌群密集",
            ["fullscreen.region_pressure.highvalue"] = "远程哨戒密集",
            ["fullscreen.region_pressure.extraction"] = "争夺式出口",
            ["fullscreen.region_pressure.default"] = "轻度巡逻",
            ["fullscreen.region_loot.highrisk"] = "偏合金回收",
            ["fullscreen.region_loot.highvalue"] = "偏研究回收",
            ["fullscreen.region_loot.extraction"] = "有机会出现工具缓存",
            ["fullscreen.region_loot.default"] = "废料与医疗补给",
            ["fullscreen.craft.no_recipe"] = "无制作配方。",
            ["fullscreen.craft.no_resources"] = "基地资源不足。",
            ["fullscreen.craft.invalid_recipe"] = "配方数据无效。",
            ["fullscreen.craft.stash_full"] = "基地仓储已满。",

            ["inventory.base_storage"] = "基地仓储",
            ["inventory.base_storage_meta"] = "在基地容器和部署包之间拖拽物品。",
            ["inventory.base_stash"] = "基地仓储",
            ["inventory.deployment_pack"] = "部署包",
            ["inventory.base_resources_auto"] = "资源与回收件会自动沉淀到基地仓储。",
            ["inventory.quick_slots_title"] = "快捷栏",
            ["inventory.quick_slots_value"] = "已绑定消耗品",
            ["inventory.quick_slots_meta"] = "战斗中可直接使用的快捷栏位。",
            ["inventory.slot_button"] = "栏位 {0}",
            ["inventory.binding_hint"] = "将鼠标悬停在携带中的消耗品上时，点击栏位或按 4 / 5 / 6 / 7 进行绑定；无目标时点击可清空。",
            ["inventory.transfer"] = "物资转移",
            ["inventory.transfer_meta"] = "在附近地面与携行包之间拖拽物品；拖到地面可丢弃当前物品。",
            ["inventory.nearby_ground"] = "附近地面掉落",
            ["inventory.carried_pack"] = "携行包",
            ["inventory.launch_pack_meta"] = "只有已装入的物品会复制到下一次行动。",
            ["inventory.adjust_supplies"] = "调整补给",
            ["inventory.launch_resources"] = "资源会直接结算入基地库存，部署包只接受可重复使用的消耗品。",
            ["inventory.quick_button.empty"] = "{0}  空",
            ["inventory.quick_button.item"] = "{0}  {1}{2}",
            ["inventory.instruction.locker"] = "左键拾取物品，放到其他格子即可移动；按 R 旋转，按 Z 自动整理。",
            ["inventory.instruction.launch"] = "左键在仓储和部署包之间移动消耗品；按 R 旋转，按 Z 自动整理。",
            ["inventory.instruction.combat"] = "左键从地面或背包拾取物品；放到背包可收纳，放到地面可丢弃；按 R / Z 旋转或自动整理。",
            ["inventory.holding"] = "手持：{0}{1}",
            ["inventory.blocked_launch"] = " / 不可放入部署包",

            ["hud.health"] = "生命模组 {0} / {1}",
            ["hud.wave"] = "区域威胁 {0:00} / 击杀 {1}",
            ["hud.enemy"] = "活动目标 {0} / 刷新压力 {1}",
            ["hud.dash"] = "冲刺链路 {0:P0}",
            ["hud.dash_ready"] = "冲刺链路 就绪",
            ["hud.boss"] = "区域主核 {0} / 阶段 {1}",
            ["hud.center_title"] = "战术链路中断",
            ["hud.center_hint"] = "返回基地完成结算，然后重新部署。",
            ["hud.reload"] = "换弹 {0}%",

            ["readiness.ready"] = "就绪",
            ["readiness.acceptable"] = "当前地图的部署包配置可接受。",
            ["readiness.blocked"] = "受阻",
            ["readiness.no_weapon"] = "部署前至少要保留一把已装备武器。",
            ["readiness.need_heal"] = "高风险地图要求部署包内至少携带一件治疗消耗品。",
            ["readiness.need_staged"] = "进入中高风险区域前，至少先装入一件消耗品。",
            ["readiness.caution"] = "警告",
            ["readiness.warning.no_medical"] = "缺少医疗支持",
            ["readiness.warning.no_mobility"] = "缺少机动储备",
            ["readiness.warning.no_utility"] = "缺少控场物品",
            ["readiness.warning.light_payload"] = "载荷过轻",
            ["readiness.warning.empty_pack"] = "空部署包出击",
            ["readiness.warning.detail"] = "当前地图可以部署，但{0}。",

            ["combat.pickup"] = "拾取 {0}",
            ["combat.inventory_full"] = "背包已满",
            ["combat.extraction_ready"] = "撤离校验完成，等待结算确认",
            ["combat.weapon_empty"] = "{0} 空仓，按 R 换弹",
            ["combat.enemy_spawned"] = "{0} 出现",
            ["combat.boss_phase"] = "主核进入强化阶段",
            ["combat.enemy_defeated"] = "{0} 已被消灭",
            ["combat.settlement_label"] = "结算确认",
            ["combat.awaiting_settlement_down"] = "战术链路中断，确认结算后返回基地。",
            ["combat.awaiting_settlement_success"] = "行动已完成，确认结算后返回基地。",
            ["combat.hint.current_zone"] = "{0} / 威胁 {1} / 保持机动并留意巡游敌群。",
            ["combat.hint.open_area"] = "在开放区域内探索并保持机动。",
            ["combat.extract_and_settle"] = "执行撤离并进入结算。",
            ["combat.clear_zone_for_exit"] = "清空当前区域后才能操作出口。",
            ["combat.status.pen"] = "穿透",
            ["combat.status.armor"] = "装甲",
            ["combat.status.pierce"] = "贯穿",
            ["combat.down"] = "行动失败",

            ["exit.progress.advance"] = "推进校验中 {0}%",
            ["exit.progress.extract"] = "撤离校验中 {0}%",
            ["exit.progress.opening"] = "闸门开启中 {0}%",

            ["basecamp.deploy_current_map"] = "部署至当前地图",

            ["wave.boss"] = "区域主核正在接管战场",
            ["wave.melee"] = "追猎体开始从外围压近",
            ["wave.ranged"] = "射击体加入火力线",
            ["wave.charger"] = "冲锋体开始压迫位移节奏",
        },
        [EnglishLocale] = new Dictionary<string, string>(),
    };

    public static string CurrentLocale { get; private set; } = ChineseLocale;

    public static void SetLocale(string? locale)
    {
        CurrentLocale = NormalizeLocale(locale);
    }

    public static string NormalizeLocale(string? locale)
    {
        if (string.IsNullOrWhiteSpace(locale))
            return ChineseLocale;

        string normalized = locale.Trim();
        if (normalized.StartsWith("en", StringComparison.OrdinalIgnoreCase))
            return EnglishLocale;
        if (normalized.StartsWith("zh", StringComparison.OrdinalIgnoreCase))
            return ChineseLocale;

        return ChineseLocale;
    }

    public static string Text(string key)
    {
        if (ResolveTable(CurrentLocale).TryGetValue(key, out var text))
            return text;

        if (ResolveTable(ChineseLocale).TryGetValue(key, out text))
            return text;

        return key;
    }

    public static string Format(string key, params object?[] args)
    {
        return string.Format(CultureInfo.InvariantCulture, Text(key), args);
    }

    public static string QuantitySuffix(int quantity)
    {
        return quantity > 1 ? $" ×{quantity}" : string.Empty;
    }

    private static IReadOnlyDictionary<string, string> ResolveTable(string locale)
    {
        return Tables.TryGetValue(locale, out var table) ? table : EmptyTable;
    }
}
