extends Node

const BG_OUTER := Color("f0f7fa")
const BG_INNER := Color("ffffff")
const WORLD_FLOOR := Color("f4f9fc")
const WORLD_FLOOR_DEEP := Color("e8f1f5")
const WORLD_ACCENT := Color("e0ecf3")
const WORLD_DUST := Color("e0ecf3")
const WORLD_LINE := Color("dce8f0")
const WORLD_LINE_STRONG := Color("c8dce6")

const OBSTACLE_FILL := Color("ebf3f8")
const OBSTACLE_INNER := Color("f4f9fc")
const OBSTACLE_EDGE := Color("9fb8c6")
const OBSTACLE_SHADOW := Color("bacdd8")
const OBSTACLE_WALL := Color("ebf3f8")
const OBSTACLE_COVER := Color("e2edf4")
const OBSTACLE_STATION := Color("e6f0ea")
const OBSTACLE_LOCKER := Color("f0ebd9")

const MINIMAP_BG := Color("ffffff")
const MINIMAP_BORDER := Color("4db9e6")
const MINIMAP_OBSTACLE := Color("bacdd8")
const MINIMAP_PLAYER := Color("4db9e6")
const MINIMAP_ENEMY := Color("ff6b6b")
const MINIMAP_MARKER := Color("ffb033")

const ARENA_FILL := Color("f4f9fc")
const ARENA_CORE := Color("4db9e6")
const GRID := Color("dce8f0")
const FRAME := Color("4db9e6")
const FRAME_SOFT := Color("9bd4eb")
const PANEL_LINE := Color("4db9e6")
const PANEL_WARM := Color("ffb033")

const PLAYER_BODY := Color("ffffff")
const PLAYER_EDGE := Color("63cff5")
const PLAYER_CORE := Color("1e9fe0")

const ACCENT := Color("ff9d4d")
const ACCENT_SOFT := Color("ffcc8f")
const RETICLE := Color("2a5870")
const SHOT := Color("ffb066")
const DASH := Color("4ebeea")
const DANGER := Color("e46d61")
const WARNING := Color("d9a858")

const ENEMY_EDGE := Color("143245")
const ENEMY_MELEE := Color("ff8d76")
const ENEMY_MELEE_GLOW := Color("ffb89a")
const ENEMY_RANGED := Color("ffc168")
const ENEMY_RANGED_GLOW := Color("ffddb2")
const ENEMY_CHARGER := Color("ff6686")
const ENEMY_CHARGER_GLOW := Color("ff9eb0")
const ENEMY_BOSS := Color("ff5d4c")
const ENEMY_BOSS_GLOW := Color("ff9d74")
const ENEMY_PROJECTILE := Color("ff875c")

const UI_TEXT := Color("143245")
const UI_MUTED := Color("6a8c9e")
const UI_PANEL := Color("ffffff")
const UI_ACTIVE := Color("e8f4fa")
